apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodb
  labels:
    db: mongo
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: mongodb-container
        image: mongo
        ports:
          - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
             secretKeyRef:
               name: secret-data
               key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
               name: secret-data
               key: password
        readinessProbe: 
          tcpSocket:
            port: 27017
          initialDelaySeconds: 20

   # this is from directly envornment variable file  config map
   #     envFrom:
   #     - configMapRef:
   #    name: mongodb-env
   #
   #    this is  from key reference
            #env: 
            #- name: MONGO_INITDB_ROOT_USERNAME
            #valueFrom:
            #configMapKeyRef:
            # name: mongodb-env
            # key: MONGO_INITDB_ROOT_USERNAME

            #- name: MONGO_INITDB_ROOT_PASSWORD
            #valueFrom:
            #configMapKeyRef:
            # name: mongodb-env
            # key: MONGO_INITDB_ROOT_PASSWORD
        volumeMounts:
        - mountPath: /data/db
          name: test-vol
      volumes: 
      - name: test-vol
        persistentVolumeClaim:
          claimName: mongopvc

---
      
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongopvc
  labels:
    type: local
  namespace: test-ns
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  labels:
    db: mongodv
  namespace: test-ns
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
# network polices only accessed by the spring app
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: mongodb-netpol
 namespace: test-ns
spec:
  podSelector:
    matchLabels:
       app: mongo
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: spring-app-pod
      ports:
        - protocol: TCP
          port: 27017

