apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv-vol
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp
