apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.31.45.183
    path: /mnt/nfs_share/test-db
