apiVersion: v1
kind: ReplicationController 
metadata:
  name: python-rc-pod
  labels:
    app: python
  namespace: test-ns
spec:
   replicas: 1
   template:
     metadata:
       name: python-pod
       labels:
         app: python-app
     spec:
        containers:
          - name: python-container
            image: dockerhandson/python-flask-app:2
            ports:
              - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    test: service
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - port: 8080
      targetPort: 5000
